Music_proj/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands 
end

Music_proj/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Music_proj/app/models/band.rb
class Band < ApplicationRecord
validates :name, presence: true, uniqueness: true 


end

Music_proj/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


#figvapebr
class User < ApplicationRecord

    before_validation :ensure_token

    validates :email, presence: true, uniqueness: true 
    validates :session_token, presence: true, uniqueness: true   #why????
    validates :password_digest, presence: true 
    validates :password, allow_nil: true, length: {minimum:6}




    attr_reader :password 

    def self.find_user_by_credentials(email, password) 
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user 
        else  
            nil 
        end 
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_token 
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def reset_session_token! #login
        self.session_token = SecureRandom::urlsafe_base64
        self.save! 
        self.session_token 
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end


end

Music_proj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#chrlll

    helper_method :current_user, :logged_in?

    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in 
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out 
        redirect_to user_url(current_user) if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil 
        @current_user = nil 
    end

end

Music_proj/app/controllers/bands_controller.rb
class BandsController <ApplicationController

    def index 
        @bands = Band.all
        render :index 
    end

    def new 
        @band = Band.new 
        render :new
    end

    def create 
        @band = Band.new(band_params)
        if @band.save 
            redirect_to bands_url 
        else  
            flash.now[:errors] = @band.errors.full_messages
            render :new 
        end 
    end

    def show 
        @band = Band.find(params[:id])
        render :show 
    end 

    # def destroy 
    #     @band = Band.find_by(parms[:band][:name])
    #     @band.destroy 
    #     redirect_to bands_url 
    # end




private 

    def band_params
        params.require(:band).permit(:name)
    end 
end 

Music_proj/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_out, only: [:new, :create]
    before_action :require_logged_in,  only: [:destroy]   #what are these????

    def new 
        @user = User.new 
        render :new
    end

    def create 
        @user = User.find_user_by_credentials(params[:user][:email], params[:user][:password])

        if @user 
            login(@user)
            redirect_to user_url(@user)
        else  
            @user = User.new(email: email)
            flash.now[:errors] = ['Invalid shiiiiii']
            render :new
        end
    end

    def destroy 
        logout!
        flash[:message] = ['we out']
        redirect_to new_session_url
    end 

end

Music_proj/app/controllers/users_controller.rb
class UsersController < ApplicationController 
    before_action :require_logged_in, only: [:show]
    # before_action :require_logged_out, only: [:new, :create]


    def new 
        @user = User.new 
        render :new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            login(@user)
            redirect_to user_url(@user)
        else  
            flash.now[:errors] = @user.errors.full_messages 
            render :new
        end
    end
    
    def show 
        @user = User.find(params[:id])
        render :show
    end 
    

private 

    def user_params 
        params.require(:user).permit(:email, :password)
    end

end

Music_proj/app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token 
        "<input type='hidden' name='authenticity_token' value='#{ form_authenticity_token}'>".html_safe
    end
end

Music_proj/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music_proj/app/views/bands/index.html.erb
<h1>Music App Not Generic</h1>

<% @bands.each do |band| %>
    <a href='<%= band_url(band[:id]) %>'><%= band.name%><br></a>
<% end %>

Music_proj/app/views/bands/new.html.erb
<h1>Register a new band yassss</h1>
<form action="bands_urls" method="POST">
<label>Band Name</label>
<input type="text" name='band[name]' value="<%= @band.name %>">
<input type="submit" value="Submit">


</form>

Music_proj/app/views/bands/show.html.erb
<%= @band.name %>


<form action="<%= band_url%>" method='POST'>
<input type="hidden" name="_method" value="DESTROY">
<input type="submit" value="delete band">
</form>

Music_proj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

    <% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <% if logged_in? %>
    <form action="<%= session_url %>" method='Post'>
      <%= auth_token %>
      <input type="hidden" name="_method" value='DELETE'>
      <input type="submit" value='Log Out'>
    </form>
  <%else%>
    <a href="<%= new_user_url %>">Sign Up</a>
    <a href="<%= new_session_url %>">Log In</a>
  <%end%>


    <%= yield %>
  </body>
</html>

Music_proj/app/views/users/new.html.erb
<h1>New User</h1>
<form id='form' action=" <%= users_url %> " method="POST">
    <%= auth_token %>
<label id="signup">Enter Email</label>
<input type="text" name="user[email]" value="<%= @user.email%>">
<label>Enter Password</label>
<input type="password" name="user[password]" value=""> <!-- value should be empty?-->
<input type="submit" value="Submit">

</form>

Music_proj/app/views/users/show.html.erb
<h1>Welcome! <%= @user.email%></h1>

<a href="<%= bands_url%>">YOUR BAND'S</a>